PREFIX=/usr/local
PATH="$PREFIX/bin:$PATH"
LP="$PREFIX/include"
CPPFLAGS="-I$LP $CPPFLAGS"
CPATH="$LP:$CPATH"
C_INCLUDE_PATH="$LP:$C_INCLUDE_PATH"
CPLUS_INCLUDE_PATH="$LP:$CPLUS_INCLUDE_PATH"
OBJC_INCLUDE_PATH="$LP:$OBJC_INCLUDE_PATH"
unset LP

LP="$PREFIX/lib"
LDFLAGS="-L$LP $LDFLAGS"
LIBRARY_PATH="$LP:$LIBRARY_PATH"
LD_LIBRARY_PATH="$LP:$LD_LIBRARY_PATH"
LD_RUN_PATH="$LP:$LD_RUN_PATH"
unset LP

LP="$PREFIX/lib/pkgconfig"
PKG_CONFIG_LIBDIR="$LP:$PKG_CONFIG_LIBDIR"
PKG_CONFIG_PATH="$PREFIX/share/pkgconfig:$LP:$PKG_CONFIG_PATH"
unset LP

export PREFIX PATH
export CPPFLAGS CPATH C_INCLUDE_PATH CPLUS_INCLUDE_PATH OBJC_INCLUDE_PATH
export LDFLAGS LIBRARY_PATH LD_LIBRARY_PATH LD_RUN_PATH
export PKG_CONFIG_LIBDIR PKG_CONFIG_PATH

CONFIG_OPTS=(
  PATH="$PATH"
  CPPFLAGS="$CPPFLAGS"
  CPATH="$CPATH"
  C_INCLUDE_PATH="$C_INCLUDE_PATH"
  CPLUS_INCLUDE_PATH="$CPLUS_INCLUDE_PATH"
  OBJC_INCLUDE_PATH="$OBJC_INCLUDE_PATH"
  LDFLAGS="$LDFLAGS"
  LIBRARY_PATH="$LIBRARY_PATH"
  LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
  LD_RUN_PATH="$LD_RUN_PATH"
  PKG_CONFIG_LIBDIR="$PKG_CONFIG_LIBDIR"
  PKG_CONFIG_PATH="$PKG_CONFIG_PATH"
)
export CONFIG_OPTS

